spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: raulklahold
    password: 6640
jpa:
  show-sql: true
  hibernate:
    ddl-auto: update
    properties:
      hibernate.format_sql: true